import 'dart:io';

import 'package:flutter/cupertino.dart';

class Global
{
  static int selectPage = 0;
  static String profileName = "User", emailID = "dummy@gmail.com";
  static File? image;
  static String userName = "", userAdd = "", userPhone = "", userPinCode = "", userCity = "", userState = "", userCountry = "";
  static TextEditingController name = TextEditingController();
  static TextEditingController email = TextEditingController();
  static GlobalKey<FormState> profileKey = GlobalKey<FormState>();
  static GlobalKey<FormState> buyNowKey = GlobalKey<FormState>();
  static List<Map<String,dynamic>> items = [
    {
      'name': 'Butter Cake',
      'image': 'build/image/cake1.png',
      'price': '499',
      'category': 'Cake',
      'gram': '350 gm',
      'star': '4.9',
      'time': '10-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Sponge Cake',
      'image': 'build/image/cake2.png',
      'price': '599',
      'category': 'Cake',
      'gram': '500 gm',
      'star': '4.2',
      'time': '15-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Biscuit Cake',
      'image': 'build/image/cake3.png',
      'price': '349',
      'category': 'Cake',
      'gram': '250 gm',
      'star': '4.6',
      'time': '20-30 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Food Cake',
      'image': 'build/image/cake4.png',
      'price': '649',
      'category': 'Cake',
      'gram': '400 gm',
      'star': '4.8',
      'time': '10-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Carrot Cake',
      'image': 'build/image/cake5.png',
      'price': '249',
      'category': 'Cake',
      'gram': '150 gm',
      'star': '3.9',
      'time': '30-40 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Banana Bread',
      'image': 'build/image/bread1.png',
      'price': '179',
      'category': 'Bread',
      'gram': '200 gm',
      'star': '3.6',
      'time': '15-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Brioche Bread',
      'image': 'build/image/bread2.png',
      'price': '349',
      'category': 'Bread',
      'gram': '150 gm',
      'star': '4.1',
      'time': '20-30 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Challah Bread',
      'image': 'build/image/bread3.png',
      'price': '89',
      'category': 'Bread',
      'gram': '100 gm',
      'star': '4.9',
      'time': '20-30 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Ciabatta Bread',
      'image': 'build/image/bread4.png',
      'price': '129',
      'category': 'Bread',
      'gram': '50 gm',
      'star': '3.4',
      'time': '10-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Cornbread Bread',
      'image': 'build/image/bread5.png',
      'price': '179',
      'category': 'Bread',
      'gram': '150 gm',
      'star': '3.8',
      'time': '30-40 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Yeast Donut',
      'image': 'build/image/donut1.png',
      'price': '229',
      'category': 'Donut',
      'gram': '250 gm',
      'star': '4.5',
      'time': '1 Hour',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Cake Donut',
      'image': 'build/image/donut2.png',
      'price': '179',
      'category': 'Donut',
      'gram': '250 gm',
      'star': '3.3',
      'time': '40-50 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Jelly Donut',
      'image': 'build/image/donut3.png',
      'price': '89',
      'category': 'Donut',
      'gram': '150 gm',
      'star': '4.4',
      'time': '2 Hour',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Cider Donut',
      'image': 'build/image/donut4.png',
      'price': '299',
      'category': 'Donut',
      'gram': '300 gm',
      'star': '4.9',
      'time': '10-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Glazed Donut',
      'image': 'build/image/donut5.png',
      'price': '99',
      'category': 'Donut',
      'gram': '100 gm',
      'star': '4.2',
      'time': '20-40 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Wafer Biscuits',
      'image': 'build/image/biscuit1.png',
      'price': '59',
      'category': 'Biscuit',
      'gram': '50 gm',
      'star': '4.5',
      'time': '10-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Ginger Biscuits',
      'image': 'build/image/biscuit2.png',
      'price': '99',
      'category': 'Biscuit',
      'gram': '100 gm',
      'star': '3.3',
      'time': '25-30 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Digestive Biscuits',
      'image': 'build/image/biscuit3.png',
      'price': '20',
      'category': 'Biscuit',
      'gram': '50 gm',
      'star': '4.2',
      'time': '10-20 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Bourbon Biscuits',
      'image': 'build/image/biscuit4.png',
      'price': '29',
      'category': 'Biscuit',
      'gram': '50 gm',
      'star': '3.7',
      'time': '40-50 Min',
      'cart': false,
      'quantity': 1,
    },
    {
      'name': 'Oreo Biscuits',
      'image': 'build/image/biscuit5.png',
      'price': '49',
      'category': 'Biscuit',
      'gram': '50 gm',
      'star': '4.0',
      'time': '50-60 Min',
      'cart': false,
      'quantity': 1,
    },
  ];
  static List<Map<String,dynamic>> myOrder = [];
}
